version: '3.8'

services:
  api:
    image: api-web-scrapping:latest
    container_name: api-web-scrapping-prod
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - AUTH_JWT_SECRET=${JWT_SECRET}
      - AUTH_TOKEN_DURATION=24h
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: api-web-scrapping-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    networks:
      - api-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

networks:
  api-network:
    driver: bridge
